version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db:/var/lib/mysql

  devops-project:
    container_name: kaddem
    image: lamis11/backend:4.0
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8089:8089"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: